### PR TITLE
docs(checkbox): docs for the label slot

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Added docs for the label slot.

**Solving issue**  
Fixes: https://tegel.atlassian.net/browse/DTS-2022

**How to test**  
1. Go to Components -> Checkbox
2. Check under Notes and check the slot section.

### CODE REVIEW

**Comment by timrombergjakobsson** [comment]
> **Describe pull-request** Added docs for the label slot.
> 
> **Solving issue** Fixes: https://tegel.atlassian.net/browse/DTS-2022
> 
> **How to test**
> 
> 1. Go to Components -> Checkbox
> 2. Check the docs and the slot section.

You mean the "Notes" section?

**Comment by mJarsater** [comment]
> > **Describe pull-request** Added docs for the label slot.
> > **Solving issue** Fixes: https://tegel.atlassian.net/browse/DTS-2022
> > **How to test**
> > 
> > 1. Go to Components -> Checkbox
> > 2. Check the docs and the slot section.
> 
> You mean the "Notes" section?

Yes! Exactly

**Review by timrombergjakobsson — APPROVED** [review]
Looking good!

**Review by alexandereneroth — APPROVED** [review]
🌍

**Pull request merged**
