### PR TITLE
fix(tabs): correct the text color of disabled tabs

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
Corrected the color for the disabled tabs.

**Solving issue**  
Fixes: -

**How to test**  
1. Go to Tabs -> Folder
2. Check in check the styling for the disabled tab.

### CODE REVIEW

**Review by nathalielindqvist — COMMENTED** [review]
Looks like there are hover styling on the disabled tabs?

https://github.com/scania-digital-design-system/tegel/assets/48509966/1988a51f-a53d-44cc-96be-be637afbb0fc

**Review by nathalielindqvist — APPROVED** [review]
🙌

**Review by theJohnnyMe — CHANGES_REQUESTED** [review]
There seems to be an issue with Folder Tabs and 4th tab which is disabled. The color of the text looks like it is not disabled. I think the issue might be in the specificity of CSS:  
Screenshot 2023-07-05 at 10 39 35

**Review by theJohnnyMe — DISMISSED** [review]
Nice!

**Review by alexandereneroth — DISMISSED** [review]
Screenshot 2023-07-05 at 11 42 00
Looks like folder tab has the wrong disabled color in dark mode

**Review by alexandereneroth — APPROVED** [review]
💯

**Review by theJohnnyMe — APPROVED** [review]
🤘

**Pull request merged**
