### PR TITLE
feat(textfield): correct colors. 

### PR DESCRIPTION
**Pull request by timrombergjakobsson**
**Describe pull-request**  
Addressing some incorrect colors in the Texfield component. 

**Solving issue**  
Fixes: [DTS-1981](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1981)

**How to test**  
1. Go to Components -> Textfield
2. Check in the different states, types, light/dark-mode, and compare with Figma

[DTS-1981]: https://tegel.atlassian.net/browse/DTS-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by charlottelorensson** [comment]
Can't really find the color but it looks like the default placeholder is grey 500 rather than grey 600. Could that be? (The placeholder should then change to grey 500 when focused/typing)

**Comment by timrombergjakobsson** [comment]
> Can't really find the color but it looks like the default placeholder is grey 500 rather than grey 600. Could that be? (The placeholder should then change to grey 500 when focused/typing)

@charlottelorensson yes you are right. I will have a closer look at it!

**Comment by timrombergjakobsson** [comment]
> > Can't really find the color but it looks like the default placeholder is grey 500 rather than grey 600. Could that be? (The placeholder should then change to grey 500 when focused/typing)
> 
> @charlottelorensson yes you are right. I will have a closer look at it!

Hm by the way, should it not be grey-868 when typing? https://www.figma.com/file/d8bTgEx7h694MSesi2CTLF/Tegel-UI-Library?type=design&node-id=35602-174402&mode=dev and grey-500 when focused. And grey-600 when normal?

**Comment by charlottelorensson** [comment]
> Hm by the way, should it not be grey-868 when typing? https://www.figma.com/file/d8bTgEx7h694MSesi2CTLF/Tegel-UI-Library?type=design&node-id=35602-174402&mode=dev and grey-500 when focused. And grey-600 when normal?

Yes, sry‚ it is 868 when typing. Should've left typing out :)

**Comment by timrombergjakobsson** [comment]
> 

No worries :), but then those colors mentioned is correct right?

**Review by charlottelorensson — APPROVED** [review]

**Review by theJohnnyMe — APPROVED** [review]
Awesome work you two 🤘

**Pull request merged**
