### PR TITLE
docs(storybook-table): controls for overflow

### PR DESCRIPTION
**Pull request by theJohnnyMe**
## **Describe pull-request**  
Adding missing config for storybook controls on expandable story

## **Issue Linking:**  
- **No issue:** Issue spotted "on-fly"

## **How to test**  
1. Go to preview link
2. Check Table Expandable rows story
3. Check that overflow control has default "auto" and possibility to switch to "hidden" and "visible"

## **Checklist before submission**
- [ ] I have added unit tests for my changes (if applicable)
- [x] All existing tests pass
- [x] I have updated the documentation (if applicable)
- [x] Not breaking production behavior
- [x] Behavior available in storybook with documented descriptions (if applicable)
- [x] `npm run build-all` without errors

## **Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [x] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

### CODE REVIEW

**Review by ckrook — APPROVED** [review]
Looks good!

**Review by nathalielindqvist — APPROVED** [review]
Nice! 🚀

**Review by Lunkan89 — COMMENTED** [review]
aren't these changes in https://github.com/scania-digital-design-system/tegel/pull/793 also?

**Comment by theJohnnyMe** [comment]
I am bringing this back as the develop branch does not have correct controls again.

**Pull request merged**
