### PR TITLE
refactor(slider): rename scrubber to thumb

### PR DESCRIPTION
**Pull request by nathalielindqvist**
**Describe pull-request**  
Renamed all instances of "scrubber" to "thumb" to align with documentation and design.

**Solving issue**  
Fixes: [CDEP-2107](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2107)

**How to test**  
1. Go to Storybook link below
2. Check in Slider
3. Test that it still looks and works as it should

### CODE REVIEW

**Review by mJarsater — COMMENTED** [review]
The prop name changes needs to be listed in the migration docs

**Comment by nathalielindqvist** [comment]
> The prop name changes needs to be listed in the migration docs

Updated now!

**Review by theJohnnyMe — APPROVED** [review]
LGTM

**Review by timrombergjakobsson — APPROVED** [review]
Good work!

**Pull request merged**
