### PR TITLE
test(banner): add darkmode screenshot test and refactor folder structure

### PR DESCRIPTION
**Pull request by max-umain**
## **Describe pull-request**  
Adds screenshot tests for banner in light and dark modes, as well as with different background colors and banner variants.

## **Issue Linking:**  
- **Jira:** [CDEP-3645](https://tegel.atlassian.net/browse/CDEP-3645)    

## **How to test**  
_Provide detailed steps for testing, including any necessary setup._
1. Run `npm run test`
2. Visually inspect the files generated by the tests

## **Checklist before submission**
- [x] I have added unit tests for my changes (if applicable)
- [x] All existing tests pass
- [ ] I have updated the documentation (if applicable)
- [ ] Not breaking production behavior
- [ ] Behavior available in storybook with documented descriptions (if applicable)
- [x] `npm run build-all` without errors

## **Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [x] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

## **Screenshots**  
Not applicable

## **Additional context**  
None

[CDEP-3645]: https://tegel.atlassian.net/browse/CDEP-3645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nathalielindqvist — COMMENTED** [review]
Neat implementation! From what I can see you have created a new folder for these test results. Sticking to the current folder structure, with 'basic', 'default', 'information' and 'error' and having the corresponding tests in their respective folders might make it easier to maintain. Looking at the already existing screenshots it looks like they have an icon in the Banner as well, which is a visual element that would need to be tested in dark and light mode as well. Maybe there is a way to build on top of what is already there? :)

**Comment by max-umain** [comment]
@nathalielindqvist 
Thank you for the feedback :)

I now created a commit https://github.com/scania-digital-design-system/tegel/pull/880/commits/aee107855b01184452a17ae1ae5add709d41d4bc where I created a file screenshotTests.ts, that I now call from the existing test files for banner. This uses the existing index.html files for the existing tests, so the icons in those will be present in these screenshots too. 

Perhaps we could reuse the screenshotTests function in other components (for similar tickets in Jira). What do you think about this solution?

**Comment by max-umain** [comment]
Update: I removed the reusable test and created lightmode and darkmode folders in banner tests

**Review by nathalielindqvist — APPROVED** [review]
Great work! 🌟

**Comment by max-umain** [comment]
One final change: @Lunkan89 and I agreed that it's unnecessary to change html files (and the images) of the existing tests if they are e.g. lightmode with white background, so I restored the html files to how they were before

**Review by nathalielindqvist — APPROVED** [review]
Good thinking, looks nice! 🙂

**Review by Lunkan89 — APPROVED** [review]

**Comment by max-umain** [comment]
Sorry, I forgot to refactor the page.goto lines to beforeEach, pushed that commit now

**Review by Lunkan89 — APPROVED** [review]
Looks good

**Pull request merged**
