### PR TITLE
fix(table): passing on unit value with horizontalscroll

### PR DESCRIPTION
**Pull request by timrombergjakobsson**
## **Describe pull-request**  
Fixing broken horizontal scroll

## **Issue Linking:**  
- **Jira:** [CDEP-3450](https://tegel.atlassian.net/browse/CDEP-3450)    

## **How to test**  
_Provide detailed steps for testing, including any necessary setup._
1. Go to Storybook.
2. Check in Storybook
4. Enter a value for horizontal scroll

[CDEP-3450]: https://tegel.atlassian.net/browse/CDEP-3450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nathalielindqvist — APPROVED** [review]
Nice!

**Review by Lunkan89 — APPROVED** [review]

**Comment by theJohnnyMe** [comment]
Am I missing some of the props or this is expected: 

Screenshot 2024-09-02 at 09 35 08

**Review by Lunkan89 — CHANGES_REQUESTED** [review]
toolbar and footer does not follow the table width

**Review by theJohnnyMe — APPROVED** [review]
Nice one!

**Pull request merged**
