### PR TITLE
docs(storybook): sort stories alpabetically

### PR DESCRIPTION
**Pull request by timrombergjakobsson**
**Describe pull-request**  
Only a suggestion on how to handle alphabetical sorting. This way however sorts everything alphabetical but does not keep all tabs in a "tab"-folder. So they are sorted alphabetically based on prefix. One other approach would be to have them in tabs folder and then in stories-file do like we do with Table. `title: ${ComponentsFolder}/Tabs`. 

Note: Check commits, one commit is auto generated readmes added.

**Solving issue**  
Fixes: [DTS-1697](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1697)

[DTS-1697]: https://tegel.atlassian.net/browse/DTS-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mJarsater** [comment]
Should we close this one for now?

**Comment by mJarsater** [comment]
> > Should we close this one for now?
> 
> How come? Was just paused so that we could do the renaming first. And then would be picked up. Or did I miss something?

Was mostly thinking that we don't want paused PRs up. The branch will still exist so could just be reopened when this work is resumed.

**Comment by timrombergjakobsson** [comment]
> > > Should we close this one for now?
> > 
> > 
> > How come? Was just paused so that we could do the renaming first. And then would be picked up. Or did I miss something?
> 
> Was mostly thinking that we don't want paused PRs up. The branch will still exist so could just be reopened when this work is resumed.

Ah ok, yeah sure however. I can also resume it now.

**Comment by alexandereneroth** [comment]
> > > > Should we close this one for now?
> > > 
> > > 
> > > How come? Was just paused so that we could do the renaming first. And then would be picked up. Or did I miss something?
> > 
> > 
> > Was mostly thinking that we don't want paused PRs up. The branch will still exist so could just be reopened when this work is resumed.
> 
> Ah ok, yeah sure however. I can also resume it now.

If you make a new branch instead you dont have to deal with the merge conflict, just a suggestion

**Comment by timrombergjakobsson** [comment]
> > > > > Should we close this one for now?
> > > > 
> > > > 
> > > > How come? Was just paused so that we could do the renaming first. And then would be picked up. Or did I miss something?
> > > 
> > > 
> > > Was mostly thinking that we don't want paused PRs up. The branch will still exist so could just be reopened when this work is resumed.
> > 
> > 
> > Ah ok, yeah sure however. I can also resume it now.
> 
> If you make a new branch instead you dont have to deal with the merge conflict, just a suggestion

Yes, good suggestion, have not had the time to look at this. So will do that!

**Pull request closed without merging**
