### PR TITLE
test(banner): darkmode coverage

### PR DESCRIPTION
**Pull request by max-umain**
## **Describe pull-request**  
Adds dark mode test for the default test for banner.

## **Issue Linking:**  
Not applicable

## **How to test**  
Run `npm run test`
Visually inspect the files generated by the tests

## **Checklist before submission**
- [x] I have added unit tests for my changes (if applicable)
- [x] All existing tests pass
- [ ] I have updated the documentation (if applicable)
- [ ] Not breaking production behavior
- [ ] Behavior available in storybook with documented descriptions (if applicable)
- [ ] `npm run build-all` without errors

## **Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [x] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

## **Screenshots**  
"_Include before/after screenshots for UI changes._" not applicable

## **Additional context**  
None

### CODE REVIEW

**Review by timrombergjakobsson — APPROVED** [review]
Nice one @max-umain! Just make sure to rebase!

**Review by nathalielindqvist — COMMENTED** [review]
Awesome work @max-umain! 🥳 I have a few comments, just rest assure that they're not targeted towards you - we're just trying to keep this massive product of ours as consistent as we can 😁 
In this repository we are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in order to keep neat logs. So it would be great if you could rename the title of this PR to something that follows the conventional commits, starting first with the type of commit it is, followed by the effected component within parentheses and finished of with some descriptive words. So in this case it could look something like "test(banner): dark mode" or anything similar. In the future it would also be awesome if you could follow a similar convention when naming your branches going forward, but no worries in this particular PR 😄 

I know you haven't gotten access to Jira yet, are you collaborating with Johan in what to work on for the moment? The ticket regarding Banner has several steps to test around dark mode, is the plan for you to do all of them or was this the agreed upon level for you to start out with? Just so we know what has already been done so we note it down in the Jira ticket, wouldn't want to end up working on something that has already been taken care of 😁

**Comment by Lunkan89** [comment]
> Awesome work @max-umain! 🥳 I have a few comments, just rest assure that they're not targeted towards you - we're just trying to keep this massive product of ours as consistent as we can 😁 In this repository we are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in order to keep neat logs. So it would be great if you could rename the title of this PR to something that follows the conventional commits, starting first with the type of commit it is, followed by the effected component within parentheses and finished of with some descriptive words. So in this case it could look something like "test(banner): dark mode" or anything similar. In the future it would also be awesome if you could follow a similar convention when naming your branches going forward, but no worries in this particular PR 😄
> 
> I know you haven't gotten access to Jira yet, are you collaborating with Johan in what to work on for the moment? The ticket regarding Banner has several steps to test around dark mode, is the plan for you to do all of them or was this the agreed upon level for you to start out with? Just so we know what has already been done so we note it down in the Jira ticket, wouldn't want to end up working on something that has already been taken care of 😁

Yes I have assigned the tickets to me for now.

**Comment by timrombergjakobsson** [comment]
> > Awesome work @max-umain! 🥳 I have a few comments, just rest assure that they're not targeted towards you - we're just trying to keep this massive product of ours as consistent as we can 😁 In this repository we are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in order to keep neat logs. So it would be great if you could rename the title of this PR to something that follows the conventional commits, starting first with the type of commit it is, followed by the effected component within parentheses and finished of with some descriptive words. So in this case it could look something like "test(banner): dark mode" or anything similar. In the future it would also be awesome if you could follow a similar convention when naming your branches going forward, but no worries in this particular PR 😄
> > I know you haven't gotten access to Jira yet, are you collaborating with Johan in what to work on for the moment? The ticket regarding Banner has several steps to test around dark mode, is the plan for you to do all of them or was this the agreed upon level for you to start out with? Just so we know what has already been done so we note it down in the Jira ticket, wouldn't want to end up working on something that has already been taken care of 😁
> 
> Yes I have assigned the tickets to me for now.

Yes, @max-umain if you look at for example this [pr](https://github.com/scania-digital-design-system/tegel/pull/704), there you can see the syntax in the title.

**Comment by max-umain** [comment]
I totally understand, thanks for the feedback :) @nathalielindqvist 

I think this was agreed upon between me and @Lunkan89 before I had access to Jira. After looking at the Jira ticket and realizing it was quite different from this I thought it would make more sense to just make a new PR for a separate branch for that, and then we can delete this PR and branch. The new PR: #880

**Comment by Lunkan89** [comment]
Then we should close this one, correct @max-umain

**Pull request closed without merging**
