### PR TITLE
build: stencil@4.7.0

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
This PR upgrades our core package to use the latest Stencil version: 4.7.0.

**NOTE**
This PR is based off of https://github.com/scania-digital-design-system/tegel/pull/374, this is due to jest and puppeteer being removed in that PR. This is a prerequisite for us to move to 4.7.0.
This PR should NOT be merged before  https://github.com/scania-digital-design-system/tegel/pull/374

**Solving issue**  
Fixes: [CDEP-2908](https://tegel.atlassian.net/browse/CDEP-2908)

**How to test**  
1. Check out branch
2. Run `npm install` in packages/core
3. Run `npm run build`

[CDEP-2908]: https://tegel.atlassian.net/browse/CDEP-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by timrombergjakobsson — CHANGES_REQUESTED** [review]
Needs rebase!

**Comment by mJarsater** [comment]
> Needs rebase!

I don't think this should be rebased now. Like specified in the description, this PR isn't really relevant until the playwright PR has been merged. So I think we can leave it until then.

**Comment by timrombergjakobsson** [comment]
> > Needs rebase!
> 
> I don't think this should be rebased now. Like specified in the description, this PR isn't really relevant until the playwright PR has been merged. So I think we can leave it until then.

Alright! FYI, tried it out locally and compiles.

**Comment by mJarsater** [comment]
> > > Needs rebase!
> > 
> > 
> > I don't think this should be rebased now. Like specified in the description, this PR isn't really relevant until the playwright PR has been merged. So I think we can leave it until then.
> 
> Alright! FYI, tried it out locally and compiles.

Steak sauce!

**Review by theJohnnyMe — APPROVED** [review]
Tested, installes, builds and runs good on Node 20.

**Comment by theJohnnyMe** [comment]
You will get some conflicts due to the "hotfix" release branch we merged in develop in the Tegel react wrappers release.  Ping if you need some help there, but in a nutshell @scania/tegel-react should have 1.1.0 as version too.

**Pull request closed without merging**
