### PR TITLE
chore: fix Windows test script

### PR DESCRIPTION
**Pull request by nathalielindqvist**
**Describe pull-request**  
Refactored the unit testing script to be able to run on Windows OS.

**Solving issue**  
Fixes: [CDEP-2969](https://tegel.atlassian.net/jira/software/projects/CDEP/boards/1?selectedIssue=CDEP-2969)

**How to test**  
1. Check out branch
2. Cd into packages/core
3. Run "npm run test"

[CDEP-2969]: https://tegel.atlassian.net/browse/CDEP-2969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by timrombergjakobsson — APPROVED** [review]
Great work! Maybe we should have a more descriptive name for the file "test.js"?

**Comment by nathalielindqvist** [comment]
> Great work! Maybe we should have a more descriptive name for the file "test.js"?

Yes good idea!

**Comment by alexandereneroth** [comment]
> > Great work! Maybe we should have a more descriptive name for the file "test.js"?
> 
> Yes good idea!

What about run-tests-in-docker.js ?
I think the name should mention that it tests

**Comment by timrombergjakobsson** [comment]
> I think the name should mention that it tests

Yes, the allmighty AI provided some alternatives. But tld;r, something descriptive. 

Skärmavbild 2023-11-07 kl  11 03 36

**Comment by nathalielindqvist** [comment]
> > > Great work! Maybe we should have a more descriptive name for the file "test.js"?
> > 
> > 
> > Yes good idea!
> 
> What about run-tests-in-docker.js ? I think the name should mention that it tests

Name updated!

**Review by theJohnnyMe — APPROVED** [review]
Nice, works here too!

**Pull request merged**
