### PR TITLE
fix: move the border of the expanded table row to the bottom of the expanded section

### PR DESCRIPTION
**Pull request by adarean5**
**Describe pull-request**  
There is a visual issue in the expandable row. When the row is in the expanded state, the border is between the row and the expanded section instead of at the bottom of the expanded section. There is also no border at the bottom of the expanded section. If multiple rows are expanded, it looks like the expanded section is a part of the next row (check the issue linked below for more information).

This PR fixes the issue. The border between the row and the expandable section is moved to the bottom of the expandable section instead. This makes it more obvious that the row and the expandable section are the same entity and it also adds a visual divider between the expandable section and the next row.

**Solving issue**  
Fixes: [574](https://github.com/scania-digital-design-system/tegel/issues/574)

**How to test**  
1. Run the storybook
2. Go to the story _Components / Table / Expandable rows
3. Expand the rows

**Checklist before submission**
- [x] I have added unit tests for my changes (if applicable)
- [x] All existing tests pass
- [x] I have updated the documentation (if applicable)

**Suggested test steps**
- [x] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [x] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

**Screenshots**  
Before:
image

After:
image

### CODE REVIEW

**Comment by adarean5** [comment]
Some tests for the filtering table were broken before I made any changes. I consulted with @theJohnnyMe and there is a [separate PR for fixing them](https://github.com/scania-digital-design-system/tegel/pull/572)
I decided to only update the tests that were affected by my changes to limit the scope.

The readme file was also automatically updated.

**Comment by theJohnnyMe** [comment]
@adarean5  - Feel free to pull latest develop and rebase your branch with it. I have merged my PR with test optimization. In merge conflict I choose changes coming from develop. After you rebase it do `git push --force` otherwise you might end up in rebase and pull/push hell.

**Comment by theJohnnyMe** [comment]
Code changes look good to me, but lets hear what colleagues designers say too. No matter what, nice work and thanks for contribution @adarean5 ;)

**Review by timrombergjakobsson — APPROVED** [review]
LGTM!

**Comment by adarean5** [comment]
@theJohnnyMe - I updated the branch with the latest changes that you added to the develop branch and now all the tests are passing locally!

**Comment by adarean5** [comment]
There are examples in the docs that show screenshots of the expandable table (https://tegel.scania.com/components/table).
Should we also update those screenshots to match the changes? I'm fairly new to the project so I'm not sure what the proper way to update the docs is, but I suppose that's probably managed before each release, rather than merging changes into develop.

Just something to keep in mind.

**Comment by timrombergjakobsson** [comment]
> There are examples in the docs that show screenshots of the expandable table (https://tegel.scania.com/components/table). Should we also update those screenshots to match the changes? I'm fairly new to the project so I'm not sure what the proper way to update the docs is, but I suppose that's probably managed before each release, rather than merging changes into develop.
> 
> Just something to keep in mind.

Yes! You are totally right, that we need to do so thanks for pointing that out. However the update of the docs there, is done in a separate app/repository. Will create a ticket related to this!

**Review by theJohnnyMe — APPROVED** [review]
Great work Jernej, we appreciate your contribution a lot! 🚀

**Comment by theJohnnyMe** [comment]
> > There are examples in the docs that show screenshots of the expandable table (https://tegel.scania.com/components/table). Should we also update those screenshots to match the changes? I'm fairly new to the project so I'm not sure what the proper way to update the docs is, but I suppose that's probably managed before each release, rather than merging changes into develop.
> > Just something to keep in mind.
> 
> Yes! You are totally right, that we need to do so thanks for pointing that out. However the update of the docs there, is done in a separate app/repository. Will create a ticket related to this!

Yes, what Tim said ;) We need to get update from designers in Figma and export new images to our CMS behind tegel.scania.com. I would say you do not have to worry about it, but if you are curious we can show how that repo works :) Just let me know in case you are.

**Comment by adarean5** [comment]
That would be awesome. Perhaps we could set up an intro meeting to demo the docs repo. If nothing else, it would be a great learning opportunity for me 😄

**Pull request merged**
