### PR TITLE
fix(side-menu) remove extra space to the right of a collapsed side menu item in desktop

### PR DESCRIPTION
**Pull request by patrikhultgren**
## **Styling problem**  
Adjusts the styling to remove extra space to the right of a collapsed side menu item in desktop.

## **Issue Linking:**
- **GitHub:** https://github.com/scania-digital-design-system/tegel/issues/620  

## **How to test**  
_Provide detailed steps for testing, including any necessary setup._
1. Go to https://tds-storybook.tegel.scania.com/?path=/docs/components-side-menu--default
2. Check Collapsible and Collapsed.
3. Look at the canvas.

## **Suggested test steps**
- [x] Browser testing (Chrome, Firefox)

## **Screenshots**  
This is how the bug looks like:
side-menu

This is how it looks like when it's resolved:
side-menu-resolved

### CODE REVIEW

**Comment by patrikhultgren** [comment]
I can confirm the expected behaviour in Storybook at Amplify.

**Review by timrombergjakobsson — COMMENTED** [review]
Nice one! Although I'm a bit bothered about that it does not look fully aligned when side menu is opened. As we can see in the screenshot. Maybe we could tweak the `--side-menu-width` variable also, like 1px?
Skärmavbild 2024-05-21 kl  11 27 48

**Comment by patrikhultgren** [comment]
Of course @timrombergjakobsson, it's done!

**Review by nathalielindqvist — APPROVED** [review]
Nice catch, thank you for the contribution! 🎉

**Review by theJohnnyMe — APPROVED** [review]
Nice catch, good 👀 !
Thank you for contribution buddy!
LGTM!

**Comment by patrikhultgren** [comment]
It was a pleasure:)

**Review by timrombergjakobsson — APPROVED** [review]
Awesome stuff! Thanks for the contribution!

**Pull request merged**
