### PR TITLE
fix(toast): enable for runtime updates of the hidden prop

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
This PR enables for runtime updates of the `hidden` prop present on the tds-toast.

**Solving issue**  
Fixes: -

**How to test**  
1. Update the `hidden` prop of the Toast in runtime
2. Make sure it hides/shows

### CODE REVIEW

**Comment by timrombergjakobsson** [comment]
Is this one related to any known issues?

**Comment by mJarsater** [comment]
> Is this one related to any known issues?

Nope, I just found the issue the React demo page

**Review by alexandereneroth — APPROVED** [review]
nice catch

**Review by theJohnnyMe — APPROVED** [review]
Nice improvement. 
In case you have time add Storybook control for "hidden" prop. We have it for the modal, so I think it would be good to have it for this one too, what do you think?

**Pull request merged**
