### PR TITLE
feat(toast): align slots

### PR DESCRIPTION
**Pull request by mJarsater**
**Describe pull-request**  
 - Alignes slot names
 - Simplifies logic for conditional rendering of slots vs props.

**Solving issue**  
Fixes: https://tegel.atlassian.net/browse/DTS-1952

**How to test**  
1. Go to storybook
2. Check in Components -> Toast
3. Test the controls and check the styles.

### CODE REVIEW

**Review by alexandereneroth — DISMISSED** [review]
Nice. Might be nice if the way the slot is styled is aligned with what you did in banner though.

**Comment by mJarsater** [comment]
> Nice. Might be nice if the way the slot is styled is aligned with what you did in banner though.

Agree, will fix

**Comment by alexandereneroth** [comment]
> > Nice. Might be nice if the way the slot is styled is aligned with what you did in banner though.
> 
> Agree, will fix

Hmm actually i think you didnt do that thing, but perhaps you saw something else, great!

**Review by alexandereneroth — DISMISSED** [review]
nice

**Review by nathalielindqvist — APPROVED** [review]
LGTM!

**Review by alexandereneroth — APPROVED** [review]

**Review by nathalielindqvist — DISMISSED** [review]

**Review by nathalielindqvist — DISMISSED** [review]

**Review by alexandereneroth — DISMISSED** [review]

**Review by alexandereneroth — APPROVED** [review]

**Review by nathalielindqvist — APPROVED** [review]

**Pull request merged**
