### PR TITLE
fix: reseting pagination if number of pages changes

### PR DESCRIPTION
**Pull request by Lunkan89**
## **Describe pull-request**  
Fixing pagination bug.

## **Issue Linking:**  
_Choose one of the following options_
- **Jira:** Add ticket number after `CDEP-`: [CDEP-](https://tegel.atlassian.net/browse/CDEP-)    
- **GitHub:** Include issue link  
- **No issue:** Describe the problem being solved.  

## **How to test**  
_Provide detailed steps for testing, including any necessary setup._
1. Go to amplify -> tables  -> pagination
2. Go to last page
3. Change number of pages

## **Checklist before submission**
- [ ] I have added unit tests for my changes (if applicable)
- [x] All existing tests pass
- [ ] I have updated the documentation (if applicable)
- [ ] Not breaking production behavior
- [x] Behavior available in storybook with documented descriptions (if applicable)
- [x] `npm run build-all` without errors

### CODE REVIEW

**Review by nathalielindqvist — COMMENTED** [review]
Not sure if this is intended behavior, but the Table displays "of NaN pages" unless you have entered a number for "Pages"
Screenshot 2024-10-08 at 13 09 06

**Comment by Lunkan89** [comment]
> Not sure if this is intended behavior, but the Table displays "of NaN pages" unless you have entered a number for "Pages" Screenshot 2024-10-08 at 13 09 06
@nathalielindqvist you are correct, fixed the `NaN`-bug. Although the reset of the page value to 1 seems to be storybook reloading on control input. I changed it to set the value of number of pages when rows per page changes :)

**Review by ckrook — APPROVED** [review]

**Comment by ckrook** [comment]
Looks good to me! 🥇  This only thing I can see is the test failing. Could you have a look? @Lunkan89 😊

**Review by timrombergjakobsson — APPROVED** [review]
LGTM!

**Review by nathalielindqvist — APPROVED** [review]
Awesome!

**Pull request merged**
