### PR TITLE
fix(css): headline-05 updated to correct value

### PR DESCRIPTION
**Pull request by alfredskeden**
**Describe pull-request**  
Updated values for headline-05 to correct values according to figma.

**Solving issue**  
_In case of GitHub issue add # plus the number of the issue (for example #123) OR if it is Azure then AB# and number of ticket_
Fixes: [CDEP-3034](https://tegel.atlassian.net/browse/CDEP-3034)

**How to test**  
1. Go to storybook
2. Check so that headline-05 text is 16px instead of 14px

**Suggested test steps**
- [x] Browser testing (Chrome, Safari, Firefox) 
- [x] Design/controls/props is aligned with other components 

**Additional context**  
We need to check that modal title still wants to have tds-headline-05 as class after this change.

[CDEP-3034]: https://tegel.atlassian.net/browse/CDEP-3034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alfredskeden** [comment]
Strangely enough it does not work. It still gets the 14 pixels... It does not build the css after my updates and I don't know why :(

**Comment by timrombergjakobsson** [comment]
I think this one is lacking: https://github.com/scania-digital-design-system/tegel/blob/fix/CDEP-3034-headline-05-wrong-size/typography/scania-fonts-vars.scss#L18

**Comment by alfredskeden** [comment]
> I think this one is lacking:
> 
> https://github.com/scania-digital-design-system/tegel/blob/3a04f3499bdd2e4a50a4b4d4ef452653bd1fbe39/typography/scania-fonts-vars.scss#L18
> 
> Also make sure to `npm run build` and `npm run storybook`. Sometimes it does not pick up changes.

I knew I was missing something!! What is the difference between the core one and /typography ones?
Thanks alot @timrombergjakobsson

**Comment by timrombergjakobsson** [comment]
> > I think this one is lacking:
> > https://github.com/scania-digital-design-system/tegel/blob/3a04f3499bdd2e4a50a4b4d4ef452653bd1fbe39/typography/scania-fonts-vars.scss#L18
> > 
> > Also make sure to `npm run build` and `npm run storybook`. Sometimes it does not pick up changes.
> 
> I knew I was missing something!! What is the difference between the core one and /typography ones? Thanks alot @timrombergjakobsson

Basically what I said on standup, typography is a separate package, structural wise. Although in the same package, when you do a download. In the old tegel package it was entire separate one https://www.npmjs.com/package/@scania/typography. Now bundled together in one.

**Comment by timrombergjakobsson** [comment]
> > > I think this one is lacking:
> > > https://github.com/scania-digital-design-system/tegel/blob/3a04f3499bdd2e4a50a4b4d4ef452653bd1fbe39/typography/scania-fonts-vars.scss#L18
> > > 
> > > Also make sure to `npm run build` and `npm run storybook`. Sometimes it does not pick up changes.
> > 
> > 
> > I knew I was missing something!! What is the difference between the core one and /typography ones? Thanks alot @timrombergjakobsson
> 
> Basically what I said on standup, typography is a separate package, structural wise. Although in the same package, when you do a download. In the old tegel package it was entire separate one https://www.npmjs.com/package/@scania/typography. Now bundled together in one.

makes total sense what I just said hahah

**Comment by alfredskeden** [comment]
> makes total sense what I just said hahah

Haha totally :) it works anyway :)

**Review by timrombergjakobsson — APPROVED** [review]

**Review by theJohnnyMe — APPROVED** [review]
LGTM

**Pull request merged**
